[package]
name = "tantivy_warc_indexer"
version = "0.1.0"
authors = ["andy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warc = "*"
derive_builder = "*"
docopt = "*"
serde = { version = "*", features = ["derive"] }
tantivy = "*"
flate2 = { version = "*", features = ["zlib-ng-compat"], default-features = false }
